NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

Reshaping a Numpy Array,
Indexing & Slicing a NumPy Array,
Replacing the elements in Numpy Array,
Manipulating NumPy Array,
Performing Mathematical & Statistical Functions using NumPy

In [ ]:
#!pip install numpy

# Numpy Operations

In [ ]:
import numpy as np

Creating a 1D Array

In [ ]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Creating a 2D Array

In [ ]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
my_list=[1,2,3,4,5]
type(my_list)

list

In [ ]:
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

Creating Arrays with Zeros and Ones

In [ ]:
# Array of zeros
zeros = np.zeros((2, 3),dtype=int)
print("Array of Zeros:")
print(zeros)

Array of Zeros:
[[0 0 0]
 [0 0 0]]


In [ ]:
# Array of ones
ones = np.ones((3, 2))
print("Array of Ones:")
print(ones)

Array of Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Array with a range of values
range_array = np.arange(10)
print("Array with a Range of Values:")
print(range_array)

Array with a Range of Values:
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Array with a range of values with a step
range_array_step = np.arange(1, 10, 2)
print("Array with a Range of Values and Step:")
print(range_array_step)

Array with a Range of Values and Step:
[1 3 5 7 9]


In [ ]:
vector_row = np.array([1,2,3])

In [ ]:
vector_row

array([1, 2, 3])

In [ ]:
print(vector_row[:2])

[1 2]


In [ ]:
print(vector_row[2])

3


In [ ]:
vector_column = np.array([[1],[2],[3]])

In [ ]:
vector_column

array([[1],
       [2],
       [3]])

In [ ]:
vector_column.ndim

2

In [ ]:
print(vector_column.size)

3


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[5,9,0],[9,8,10],[5,4,3]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  3]])

In [ ]:
print(matrix[4:,1:])

[[4 3]]


In [ ]:
matrix[4,-2:]

array([4, 3])

In [ ]:
print(matrix.shape)

(5, 3)


In [ ]:
matrix.size

15

In [ ]:
print(matrix[2,1])

9


In [ ]:
print(matrix[ : , 1:2])

[[2]
 [5]
 [9]
 [8]
 [4]]


In [ ]:
print(matrix[ 2:4 , 0:2 ])

[[5 9]
 [9 8]]


In [ ]:
print(matrix[3:4,1:3])

[[ 8 10]]


In [ ]:
print(matrix.size)

15


In [ ]:
print(np.max(matrix))

10


In [ ]:
print(np.min(matrix))

0


In [ ]:
print(np.max(matrix,axis=0))

[ 9  9 10]


In [ ]:
print(np.max(matrix,axis=1))

[ 3  6  9 10  5]


In [ ]:
print(np.mean(matrix,axis=1))

[2.         5.         4.66666667 9.         4.        ]


In [ ]:
print(matrix.reshape(1,15))

[[ 1  2  3  4  5  6  5  9  0  9  8 10  5  4  3]]


In [ ]:
print(matrix.reshape(4,4))

ValueError: cannot reshape array of size 15 into shape (4,4)

In [ ]:
matrix_1 = np.array([[1,2,3],[6,5,6],[7,7,9]])

In [ ]:
matrix_1

array([[1, 2, 3],
       [6, 5, 6],
       [7, 7, 9]])

In [ ]:
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])

In [ ]:
matrix_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
print(np.add(matrix_1,matrix_2))

[[ 8 10 12]
 [10 10 12]
 [ 8  9 12]]


In [ ]:
matrix_1 + matrix_2

array([[ 8, 10, 12],
       [10, 10, 12],
       [ 8,  9, 12]])

In [ ]:
print(np.subtract(matrix_1,matrix_2))

[[-6 -6 -6]
 [ 2  0  0]
 [ 6  5  6]]


In [ ]:
matrix_1 - matrix_2

array([[-6, -6, -6],
       [ 2,  0,  0],
       [ 6,  5,  6]])

In [ ]:
print(matrix_1*matrix_2)

[[ 7 16 27]
 [24 25 36]
 [ 7 14 27]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[12, 30]])

In [ ]:
z=np.concatenate((x,y), axis=0)
z

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y.T), axis=1)
z

array([[ 1,  3, 12],
       [ 2,  4, 30]])

In [ ]:
import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
a=np.zeros((6,), dtype=int)
a

array([0, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np
a=np.zeros((6,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
import numpy as np
a=np.ones((6,1), dtype=int)
a

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
size = 5

In [ ]:
identity_matrix=np.zeros((size,size),dtype=int)

In [ ]:
identity_matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.fill_diagonal(identity_matrix,5)

In [ ]:
print(identity_matrix)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [ ]:
import numpy as np
a = np.array([[1,4,7], [2,5,8],[3,6,9]])
b=a.flatten()
b

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
b.ndim

1

In [ ]:
a.ndim

2

In [ ]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
import numpy as np
a=np.unique([1,2,3,4,3,6,2,4,9,9,0])
a

array([0, 1, 2, 3, 4, 6, 9])

In [ ]:
import numpy as np
a = np.array([[1, 1, 0], [1, 1, 0], [2, 3, 4],[5, 9, 8],[2, 3, 4]])
b=np.unique(a, axis=0)
b

array([[1, 1, 0],
       [2, 3, 4],
       [5, 9, 8]])

In [ ]:
a

array([[1, 1, 0],
       [1, 1, 0],
       [2, 3, 4],
       [5, 9, 8],
       [2, 3, 4]])

In [ ]:
import numpy as np
a = np.array([[1, 1, 5], [1, 1, 0], [2, 2, 4],[5, 5, 8],[2, 2, 4]])
a

array([[1, 1, 5],
       [1, 1, 0],
       [2, 2, 4],
       [5, 5, 8],
       [2, 2, 4]])

In [ ]:
b=np.unique(a, axis=1)
b

array([[1, 5],
       [1, 0],
       [2, 4],
       [5, 8],
       [2, 4]])

In [ ]:
import numpy as np
a=np.random.rand(5,2)
a

array([[0.92101796, 0.09501006],
       [0.21260808, 0.00932927],
       [0.62222045, 0.87536072],
       [0.70962059, 0.44149593],
       [0.97609523, 0.32163812]])

In [ ]:
import numpy as np
a=np.random.randint(5,10, size=15)
a

array([9, 6, 5, 9, 9, 5, 8, 8, 7, 6, 8, 8, 7, 8, 8])

In [ ]:
a=np.random.randint(179,size=(5,3))
a

array([[119,  26,  32],
       [157,  11,   4],
       [116,  55,  78],
       [  3,  14, 107],
       [142,  86,  36]])

In [ ]:
import numpy as np
arr = [0.23, 0.09, 1.2, 1.24, 9.99, 101.01]
r_arr = np.ceil(arr)
r_arr

array([  1.,   1.,   2.,   2.,  10., 102.])

In [ ]:
import numpy as np
arr = [0.23, 0.09, 1.2, 1.24, 9.99]
r_arr = np.floor(arr)
r_arr

array([0., 0., 1., 1., 9.])

In [ ]:
import numpy as np
arr = [0.23, 0.09, 1.2, 1.24, 9.99]
r_arr = np.round(arr)
r_arr

array([ 0.,  0.,  1.,  1., 10.])

In [ ]:
import numpy as np
b = np.array([12, 90, 380, 12, 211])
print(np.where(b>12))
a=np.where(b>12)

(array([1, 2, 4], dtype=int64),)


In [ ]:
a1= b[a]
a1

array([ 90, 380, 211])

In [ ]:
import numpy as np
npv=np.random.randint(10, size=10)
a

array([5, 9, 9, 3, 4, 7, 0, 4, 2, 0])

In [ ]:
npm=npv.reshape(2,5)
npm

array([[2, 4, 2, 8, 4],
       [5, 5, 9, 3, 0]])

Indexing & Extracting the element from Numpy Array: For Indexing Count of Row Index Starts from 0 and Count of Column Index also starts from 0

In [ ]:
npm[0,3]

8

In [ ]:
npm[1,2]

9

In [ ]:
#Slicing Numpy Array:Extracting multiple elements from Numpy Array. Here end index is excluded.

In [ ]:
npm[0:1,1:3]

array([[4, 2]])

In [ ]:
npm[1:2,0:2]

array([[5, 5]])

In [ ]:
#Mathematical & Statistical Operations on Numpy Array

Sum

In [ ]:
#We start with Numpy Array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [ ]:
npm.sum(axis=1)

array([280, 240,  60, 200])

In [ ]:
npm.sum(axis=0)

array([260, 200, 320])

Mean

In [ ]:
#Row wise
npm.mean(axis=1)

array([93.33333333, 80.        , 20.        , 66.66666667])

In [ ]:
#Column Wise
npm.mean(axis=0)

array([65., 50., 80.])

Replacing elements in Numpy Array

In [ ]:
#Consider the array as follows
import numpy as np
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [ ]:
lst2=[[110,90,80],[70,60,110],[30,10,20],[50,40,0]]
npm1=np.array(lst2)
npm1

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40,   0]])

In [ ]:
npm3=npm/npm1
npm3

C:\Users\hp\AppData\Local\Temp\ipykernel_19036\2169324652.py:1: RuntimeWarning: divide by zero encountered in true_divide
  npm3=npm/npm1


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1., inf]])

In [ ]:
#Consider the array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [ ]:
# Replace all elements of numpy array with 50
npm[:,:]=50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [ ]:
# Replace 0,0 position with 500
npm[2,2]=500
npm

array([[ 50,  50,  50],
       [ 50,  50,  50],
       [ 50,  50, 500],
       [ 50,  50,  50]])

In [ ]:
Performing Linear Algebra Operations using NumPy (Matrix Operations)

In [ ]:
import numpy as np

Multiplication of 2 Matrices (A of Shape 3x3 multiplied by B of shape 3x2 yields Matrix of shape 3X2)

In [ ]:
A=np.matrix([[1,3,4],[4,0,2]])
A

matrix([[1, 3, 4],
        [4, 0, 2]])

In [ ]:
B=np.matrix([[1,3],[0,1],[5,2]])
B

matrix([[1, 3],
        [0, 1],
        [5, 2]])

In [ ]:
C=A*B
C

matrix([[21, 14],
        [14, 16]])

Transpose of Matrix A

In [ ]:
A=np.matrix([[5,3,2],[4,0,1],[1,0,1]])
A

matrix([[5, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [ ]:
A.T

matrix([[5, 4, 1],
        [3, 0, 0],
        [2, 1, 1]])

Trace of a Matrix The trace of a matrix is the sum of the diagonal elements of the matrix

In [ ]:
print("Trace of A:", np.trace(A))

Trace of A: 6


In [ ]:
import numpy as np
a = np.array([[100,200],[23,12]])
b = np.array([[10,20],[12,21]])

In [ ]:
a

array([[100, 200],
       [ 23,  12]])

In [ ]:
b

array([[10, 20],
       [12, 21]])

In [ ]:
vdot = np.vdot(a,b)
print(vdot)   #np.vdot(a,b) = 100 *10 + 200 * 20 + 23 * 12 + 12 * 21 = 5528

5528


In [ ]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
sampleArray = numpy.arange(100, 200, 10)
sampleArray

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [ ]:
type(sampleArray)

numpy.ndarray

Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [ ]:
a = np.arange(15,56)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [ ]:
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [ ]:
import numpy as np

my_list = [1,2,3,4,5,6]

a = np.array(my_list)
l1=list(a)


In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(l1)

list

In [ ]:
a = [[1, 2], [3, 4]]
x = np.array(a)
b = x.tolist()
print(a == b)

True


In [ ]:
a=[1,2,3,4,5]
a1=np.array(a)
a1

b=list(a1)

if b==a:
    print("True")

True


In [ ]:
type(a1)

numpy.ndarray

In [ ]:
type(b)

list